name: ng2_g_signin
description: Google sign-in component for Angular2 Dart.
version: 0.2.0+3
author: ntaoo <ntaoo.g@gmail.com>
homepage: https://github.com/ntaoo/ng2_g_signin

environment:
  sdk: '>=1.13.1 <2.0.0'

dependencies:
  angular2: ^2.0.0-beta.10
  js: ^0.6.0

transformers:
- angular2