name: ng2_g_signin_site
description: A working example site of ng2_g_signin.
version: 0.0.1
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  angular2: 2.0.0-beta.16
  ng2_g_signin:
    path: ../../../ng2_g_signin
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^0.1.0
transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- dart_to_js_script_rewriter

- $dart2js:
    minify: true
    commandLineOptions:
    - --enable-experimental-mirrors
    - --trust-type-annotations
    - --trust-primitives
